language: go

go:
  - 1.12.x

env: [GO111MODULE=on]
before_install:
  - sudo add-apt-repository ppa:jonathonf/python-3.6 -y
  - sudo apt-get update
  - sudo apt install python3.6 -y

script:
  - go test -json ./... | grep -v "no test files" | grep -v "skip" > tests_log.json 2> build.log
  - cat build.log
  - cat tests_log.json
  - bash scripts/coverage.sh

after_failure:
  - curl https://raw.githubusercontent.com/report-ci/scripts/master/annotate.py | python3.6 - --tool go --input build.log

after_script:
  - python3.6 <(curl -s https://raw.githubusercontent.com/report-ci/scripts/master/upload.py)
  - bash <(curl -s https://codecov.io/bash)